### ISSUE TITLE
Error at method call cvLoadHaarClassifierCascade

### ISSUE THREAD

**Issue by vishalkadavale** [uricamic/flandmark#35]
Hello,
 I am working on windows 7 platform with jdk1.8 I am getting following error. I tried a lot but unable to find the reason why getting this error, error snap is as follows.

Exception in thread "main" java.lang.NoSuchMethodError: putMemberOffset
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
    at java.lang.Runtime.load0(Runtime.java:795)
    at java.lang.System.load(System.java:1062)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637) at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
    at org.bytedeco.javacpp.Loader.load(Loader.java:492)
    at org.bytedeco.javacpp.Loader.load(Loader.java:409)
    at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
    at detection.Example1.loadFaceCascade(Example1.java:36)
    at detection.Example1.main(Example1.java:140)
Error getting static method ID of org/bytedeco/javacpp/Loader/putMemberOffset

Please help me!
I added following libraries in project.
flandmark-1.07-0.9.jar
opencv-3.0.0-1.0.jar
opencv-3.0.0-1.0-windows-x86.jar
opencv-3.0.0-1.0-windows-x86_64.jar
javacpp-0.9.jar
javacv-0.9.jar

Also tried different versions of these libraries but not worked out.

**Comment by uricamic** [comment]
Hi @vishalkadavale, 

I am afraid I cannot help you much since I haven't written the Java interface for flandmark. 
Maybe you can try to ask the authors of that interface.

**Comment by jpsacha** [comment]
On 9/6/2016 7:08 AM, vishalkadavale wrote:

> Hello,
> I am working on windows 7 platform with jdk1.8 I am getting following 
> error. I tried a lot but unable to find the reason why getting this 
> error, error snap is as follows.
> 
> Exception in thread "main" java.lang.NoSuchMethodError: putMemberOffset
> at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
> at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
> at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
> at java.lang.Runtime.load0(Runtime.java:795)
> at java.lang.System.load(System.java:1062)
> at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637) at 
> org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
> at org.bytedeco.javacpp.Loader.load(Loader.java:492)
> at org.bytedeco.javacpp.Loader.load(Loader.java:409)
> at org.bytedeco.javacpp.opencv_core.(opencv_core.java:10)
> at detection.Example1.loadFaceCascade(Example1.java:36)
> at detection.Example1.main(Example1.java:140)
> Error getting static method ID of 
> org/bytedeco/javacpp/Loader/putMemberOffset
> 
> Please help me!
> I added following libraries in project.
> flandmark-1.07-0.9.jar
> opencv-3.0.0-1.0.jar
> opencv-3.0.0-1.0-windows-x86.jar
> opencv-3.0.0-1.0-windows-x86_64.jar
> javacpp-0.9.jar
> javacv-0.9.jar
> 
> Also tried different versions of these libraries but not worked out.
> 
> You have mismatched versions of opencv and javacpp. When you look at the 
> version of the opencv wrapper the first number (3.0.0) is OpenCV 
> version, the second number (1.0) is the JavaCPP version, but you are 
> using version 0.9.

Jarek

**Comment by uricamic** [comment]
Thanks for the answer @jpsacha!

Can I close this as solved @vishalkadavale?

**Comment by vishalkadavale** [comment]
Thanks @jpsacha , @uricamic , I tried with 1.0 version of javacv and javacpp but still getting same Error.
Is there any restriction on versions of opencv, javacpp and javacv as I'am using flandmark1.07-0.9 .
I used 0.9 version for all these jars but still getting same error.

**Comment by vishalkadavale** [comment]
Issue solved! Thank you very much @jpsacha and @uricamic .
I used flandmark1.07-1.0, flandmark-1.07-1.0-windows-x86.jar and flandmark-1.07-1.0-windows-x86_64.jar 
with opencv3.0.0 now detecting landmarks successfully.
